name: Build and Push Docker Image

on:
  # Trigger the workflow on pushes to the main branch to update the 'latest' tag
  push:
    branches: [ main ]
  # Run daily at 9:00 UTC (an hour before the Zig CI)
  schedule:
    - cron: '0 9 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current date for tag
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            ezzieyguywuf/zcad:latest
            ezzieyguywuf/zcad:${{ steps.date.outputs.date }}
          # Cache from the latest image to speed up builds
          cache-from: type=registry,ref=ezzieyguywuf/zcad:latest
          cache-to: type=inline
