name: Zig CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ezzieyguywuf/zcad:0.15.1

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run tests
      run: zig build test
  format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Check GLSL format
      run: |
        find shaders -type f \( -name "*.frag" -o -name "*.vert" \) -print0 | xargs -0 clang-format --dry-run --Werror
    - name: Check markdown format
      run: |
        pip install mdformat
        mdformat --check .
