name: Zig CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ezzieyguywuf/zcad:0.15.1

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run tests
      run: zig build test
