name: Zig Master CI

on:
  # Run on pushes to main and on PRs to main to catch breakages early.
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Run daily at 10:00 UTC (5 AM EST / 6 AM EDT).
  schedule:
    - cron: '0 10 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-on-master:
    name: Test on Zig Master
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # We must fetch submodules for the tests to work.
        submodules: recursive

    - name: Install latest Zig from master
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        set -euo pipefail

        echo "==> Finding latest successful workflow run for ziglang/zig master..."
        # Find the ID of the latest successful workflow run on the master branch of ziglang/zig
        run_id=$(gh run list --repo ziglang/zig --workflow "CI" --branch master --status success --limit 1 --json databaseId -q '.[0].databaseId')
        if [ -z "$run_id" ]; then
          echo "Error: Could not find a successful workflow run."
          exit 1
        fi
        echo "Found run ID: $run_id"

        echo "==> Finding URL for zig-linux-x86_64 artifact..."
        # Find the URL of the artifact for linux-x86_64
        artifact_url=$(gh run view --repo ziglang/zig "$run_id" --json artifacts -q '.artifacts[] | select(.name=="zig-linux-x86_64") | .url')
        if [ -z "$artifact_url" ]; then
          echo "Error: Could not find artifact URL for zig-linux-x86_64."
          exit 1
        fi
        echo "Found artifact URL: $artifact_url"

        echo "==> Downloading artifact..."
        # Download the artifact
        gh run download --repo ziglang/zig "$run_id" --name "zig-linux-x86_64" --dir ./zig-dist

        echo "==> Extracting and installing Zig..."
        # Extract the tarball and add zig to the PATH
        tar -xf ./zig-dist/zig-linux-x86_64-*.tar.xz -C ./zig-dist
        echo "$PWD/zig-dist/zig-linux-x86_64-*/" >> $GITHUB_PATH
        
        echo "==> Verifying Zig installation..."
        zig version

    - name: Run tests with Zig (master)
      run: zig build test
